### ISSUE TITLE
Pillow deprecated antialias

### ISSUE THREAD

**Issue by LAguilera22** [jessezach/RobotEyes#108]
**Describe the bug**
[Pillow 10.0.0 removed the `image.antialias` from their classes.](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants) Instead they recommend using `Image.LANCZOS or Image.Resampling.LANCZOS`.

**To Reproduce**
1. Update pillow to the latest version
2. Run any image comparison test.

**Expected behavior**
The image comparison should run successfully. 

**Screenshots**
![image](https://github.com/jessezach/RobotEyes/assets/92947756/8e923e70-406a-40cb-a0b9-5b5f756ecaa3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Chrome

**Comment by jessezach** [comment]
Thanks for the PR @kumy
