### ISSUE TITLE
Command from cmd into the test

### ISSUE THREAD

**Issue by 12jakubpavel** [jessezach/RobotEyes#97]
**Is your feature request related to a problem? Please describe.**
I need only to run tests with one CMD. 

**Describe the solution you'd like**
I would like to move this: "-d ../output -v images_dir:${img_dig}" into the tests.

**Describe alternatives you've considered**
So far, I am testing 2 CMDs, but it is unsustainable in the future.

**Comment by Sarathchandra1202** [comment]
How to run this in browser?
pls help

**Comment by Sarathchandra1202** [comment]
@12jakubpavel  can u please help me ?
How to run this in the browser?

**Comment by 12jakubpavel** [comment]
@Sarathchandra1202 I don't understand you what do you exactly want.

**Comment by jessezach** [comment]
Unfortunately the library is designed to work as requested. There are no plans to change it as of now.
